### ISSUE TITLE
Virus Detected!

### ISSUE THREAD

**Issue by YouEbr** [Flerp/RetroCake#9]
Hello,

I tried downloading "RetroCake.exe" on windows 10. Windows Defender detects a virus and deletes the file!

Have anyone reported same behavior? 

Can you do anything to make sure your exe is clean?

Thanks,

**Comment by Flerp** [comment]
I'd recommend using the .bat file if you are uncomfortable with the exe.
Basically the exe works by shoving the same batch file into a temp directory in %temp% and then launching it as administrator.
This will always show up as a virus because it is an executable that runs a batch file as admin, which can be a way to load malicious scripts.
Feel free to use the batch (.bat) file, it will work the same way, you just have to manually launch as admin.
